### PR TITLE
feat: use multi-stage docker build to reduce the image size

### PR DESCRIPTION
**Pull request by frostming**
@wey-gu I am not able to build the image locally for some IT reasons. It might be better to test it before merge

### CODE REVIEW

**Comment by wey-gu** [comment]
> @wey-gu I am not able to build the image locally for some IT reasons. It might be better to test it before merge

Sure, I'll test later :)

We should have used a multi-stage approach! THANKS!

**Comment by wey-gu** [comment]
Still there are issues in the target stage, will check later(not familiar with js)

**Comment by frostming** [comment]
I also changed the instruction to run the gateway. the `-v` option is obviously wrong.

**Review by wey-gu — APPROVED** [review]
Thanks!!!

**Comment by wey-gu** [comment]
@frostming I'll build and push with the latest build for gateway tomorrow!

Will bring this part in gh actions, too.

**Comment by wey-gu** [comment]
It seems there is something wrong in current build of gateway

```
03:49:10 ERR PuppetWeChat initBridge() exception: Failed to launch the browser process!
/wechaty_data/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory
```

As it's a puppet of a browser/puppeteer, I guess some of the libs are not just for the build stage but for the run stage.

**Comment by frostming** [comment]
Hmm, if that is the case I agree to revert this patch, since it doesn't bring much size benefit now.

**Comment by wey-gu** [comment]
we could leverage the polished structure you created, just change to put things in one stage instead of reverting, previously I just roughly pu everything as-is, which is somewhat ugly.

**Pull request merged**
